apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
spec:
  selector:
    app: logstash
  type: LoadBalancer
  ports:
    - name: beat-port
      protocol: TCP
      port: 5044
      targetPort: 5044
    - name: monitoring
      protocol: TCP
      port: 9600        
      targetPort: 9600
